name: Docker React CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx (optional but recommended for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image using Dockerfile.dev
      - name: Build Docker image for testing
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: false
          tags: simanchala9583/docker-react:test

      # Run tests inside the built Docker image
      - name: Run tests in Docker container
        run: docker run -e CI=true simanchala9583/docker-react:test npm run test
