name: Docker React CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and load the Docker image into the local Docker daemon
      - name: Build Docker image for testing
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dev
          push: false
          load: true        # <-- This is critical
          tags: simanchala9583/docker-react:test

      - name: Run tests in Docker container
        run: docker run -e CI=true simanchala9583/docker-react:test npm run test
